print("hiee the easylearn academy")
print("hiee")
print("hiee the easylearn academy")
print("hiee")
print("hiee the easylearn academy")
print("hiee")
print("hiee the easylearn academy")
print("hiee")
print("hiee the easylearn academy")
print("hiee")
print("hiee the easylearn academy")
